name: Run Brails++ tests

on: push
  # workflow_dispatch:
  # schedule:
  #   - cron: "0 5 * * *"

jobs:
  setup_and_test:
    name: Setup and run tests
    runs-on: ubuntu-latest
    environment: quoFEM

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - run: python -m pip install git+https://github.com/NHERI-SimCenter/BrailsPlusPlus
      - run: source ./runTests.sh