name: Run Brails++ tests

on: push
  # workflow_dispatch:
  # schedule:
  #   - cron: "0 5 * * *"

jobs:
  setup_and_test:
    name: Setup and run tests
    runs-on: ubuntu-latest
    # environment: quoFEM

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Tests
        env:  
          API_KEY: ${{ secrets.API_KEY }}
        run: echo "$API_KEY" > ./examples/api_key.txt
      - run: cat ./examples/api_key.txt
      # - run: python -m pip install git+https://github.com/NHERI-SimCenter/BrailsPlusPlus
      # - run: source ./runTest.sh